config/routes.rb
Rails.application.routes.draw do
  get 'say/goodmorning'

  get 'say/goodbye'

  get 'say/goodmorning'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/goodbye_controller.rb
class GoodbyeController < ApplicationController
end

app/controllers/goodmorning_controller.rb
class GoodmorningController < ApplicationController
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def goodmorning
  end

  def goodbye
    @time = Time.now
    5.times do print "cd13tt2 ! "
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goodmorning_helper.rb
module GoodmorningHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/say/goodbye.html.erb
<h1>goodbye!!</h1>
<p>see you again </p>
<p>It is now <%= @time%></p>
<p>say <%= link_to "goodmorning", say_goodmorning_path %></p>
<p>---------------------------------</p>

<p><%= 10+9 %></p>
<p><%= "hien" + " khung" %></p>
<p><%= 1.hour.from_now %></p>

app/views/say/goodmorning.html.erb
<h1>hello ! goodmorning</h1>
<p>nice too meet you </p>